### ISSUE TITLE
Buggy libraries in zeptocomjs

### ISSUE THREAD

**Issue by veryalien** [tabemann/zeptocomjs#3]
I found a couple of bugs in the versions of the libraries which come with zeptocomjs (https://tabemann.github.io/zeptocomjs/zeptocom.html), on the bottom right-hard corner Library list.
These problems dont happen when using the latest versions from the zeptoforth repository, these are probably outdated versions:

simple_font parses 8 bits in a font row instead of 7. Wide characters like 'W' and 'H' are chopped off on the leftmost pixel on a SSD1306 display.

rp2040_neopixel (neopixel module) doesn't init pins-pio-alternate. This means nothing ever lights up, ever!

Unortunately, these bugs caught me out as a complete zeptoforth newbie.

**Comment by tabemann** [comment]
On Fri, Sep 13, 2024 at 8:44 AM veryalien ***@***.***> wrote:

> I found a couple of bugs in the versions of the libraries which come with
> zeptocomjs (https://tabemann.github.io/zeptocomjs/zeptocom.html), on the
> bottom right-hard corner Library list.
> These problems dont happen when using the latest versions from the
> zeptoforth repository, these are probably outdated versions:
>
> simple_font parses 8 bits in a font row instead of 7. Wide characters like
> 'W' and 'H' are chopped off on the leftmost pixel on a SSD1306 display.
>
> rp2040_neopixel (neopixel module) doesn't init pins-pio-alternate. This
> means nothing ever lights up, ever!
>
> Unortunately, these bugs caught me out as a complete zeptoforth newbie.
>
Thank you for bringing these to my attention. It has been a while since I
have looked at zeptocomjs; I will make sure to update these.

Travis

**Comment by tabemann** [comment]
On Fri, Sep 13, 2024 at 9:50 AM Travis Bemann ***@***.***> wrote:

> On Fri, Sep 13, 2024 at 8:44 AM veryalien ***@***.***>
> wrote:
>
>> I found a couple of bugs in the versions of the libraries which come with
>> zeptocomjs (https://tabemann.github.io/zeptocomjs/zeptocom.html), on the
>> bottom right-hard corner Library list.
>> These problems dont happen when using the latest versions from the
>> zeptoforth repository, these are probably outdated versions:
>>
>> simple_font parses 8 bits in a font row instead of 7. Wide characters
>> like 'W' and 'H' are chopped off on the leftmost pixel on a SSD1306 display.
>>
>> rp2040_neopixel (neopixel module) doesn't init pins-pio-alternate. This
>> means nothing ever lights up, ever!
>>
>> Unortunately, these bugs caught me out as a complete zeptoforth newbie.
>>
> Thank you for bringing these to my attention. It has been a while since I
> have looked at zeptocomjs; I will make sure to update these.
>

These have now been updated.

Travis

**Comment by veryalien** [comment]
Thanks for updating the files. Now working as expected.
